uploads = []

[[generated]]
id = "rHpQ06x1368oyYumR-JHr"
uri = "file://artifacts/engram-mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "f-hUiEFYn8IrciUuluv73"
uri = "file://docs/01_ENGRAM_Proposal.pdf"
type = "pdf"
title = "Formalized Proposal"

[[outputs]]
id = "P-sv7qwF3IjjTwPIyU6fN"
uri = "file://docs/02_ENGRAM_Developer_Guide.pdf"
type = "pdf"
title = "Developer Document"

[[outputs]]
id = "10vPZH5_JV4mdFmY1BuxU"
uri = "file://docs/03_ENGRAM_README.pdf"
type = "pdf"
title = "README"

[[outputs]]
id = "Y-GEkJIGZB-ki3nRXt7IR"
uri = "file://docs/04_ENGRAM_User_Manual.pdf"
type = "pdf"
title = "User Manual"

[[outputs]]
id = "88WrrF4AZ8iTC99g9_hvH"
uri = "file://docs/building-the-android-apk.md"
type = "text"
title = "How to build the ENGRAM Android .apk"
