import {
  pgTable,
  serial,
  integer,
  text,
  timestamp,
  index,
  customType,
} from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { engramsTable } from "./engrams";
import { conversations } from "./conversations";

/**
 * What an engram can GENERATE as a file. This is the OUTPUT mirror of the media
 * perception (input) modalities. Derived/validated server-side; never taken from
 * raw model output.
 */
export const ARTIFACT_KINDS = ["pdf", "image", "video"] as const;
export type ArtifactKind = (typeof ARTIFACT_KINDS)[number];

/**
 * Who initiated a generation job:
 * - autonomous: the engine decided to create it (under strict caps).
 * - operator: a human pressed "create now".
 */
export const ARTIFACT_TRIGGERS = ["autonomous", "operator"] as const;
export type ArtifactTrigger = (typeof ARTIFACT_TRIGGERS)[number];

/**
 * Lifecycle of an asynchronous generation job (mirrors the media-perception job
 * lifecycle, opposite direction):
 * - pending: queued, awaiting the artifact worker.
 * - processing: the worker has claimed it and is generating.
 * - completed: bytes generated + stored in engram_artifact_blobs.
 * - failed: generation errored (or timed out); `error` carries the reason.
 * - canceled: explicitly canceled by an operator before completion.
 *
 * Status is set ONLY by server-side logic (create route + worker), never by model
 * output. Unknown values are treated as inert.
 */
export const ARTIFACT_JOB_STATUSES = [
  "pending",
  "processing",
  "completed",
  "failed",
  "canceled",
] as const;
export type ArtifactJobStatus = (typeof ARTIFACT_JOB_STATUSES)[number];

/** Postgres `bytea` column holding raw generated bytes as a Node Buffer. */
const bytea = customType<{ data: Buffer; default: false }>({
  dataType() {
    return "bytea";
  },
});

/**
 * A piece of content an engram generated (or is generating), plus its job
 * lifecycle. The raw bytes live in `engram_artifact_blobs` (1:1) so list/status
 * queries never drag megabytes into memory — this table carries metadata only.
 *
 * `engramId` is NOT NULL: a generated artifact is always authored by one engram
 * (unlike a perceived upload, which can be operator-only). `conversationId` is
 * set when the artifact is surfaced inside a chat thread (e.g. an engram that
 * self-initiates by sharing what it made).
 *
 * This is a SEPARATE subsystem from media perception on purpose: perception is
 * provenance-pinned to OBSERVED, generation to GENERATED — they must never share
 * a write path. Nothing here ever lets model output choose status/provenance.
 */
export const engramArtifactsTable = pgTable(
  "engram_artifacts",
  {
    id: serial("id").primaryKey(),
    engramId: integer("engram_id")
      .notNull()
      .references(() => engramsTable.id, { onDelete: "cascade" }),
    /** The chat thread this artifact was shared into, if any. */
    conversationId: integer("conversation_id").references(
      () => conversations.id,
      { onDelete: "set null" },
    ),
    /** One of ARTIFACT_TRIGGERS — set by the create route / engine, never the model. */
    trigger: text("trigger").notNull(),
    /** One of ARTIFACT_KINDS — validated on create, never taken from model output. */
    kind: text("kind").notNull(),
    /** Working title for the piece. */
    title: text("title").notNull(),
    /** What the engram/operator asked to create — the generation brief. */
    prompt: text("prompt").notNull(),
    /** Which provider produced it (e.g. "local-pdf-lib", "cloud-image"). Set on completion. */
    provider: text("provider"),
    /** MIME of the produced file. Set on completion. */
    mimeType: text("mime_type"),
    /** Suggested download filename. Set on completion. */
    filename: text("filename"),
    sizeBytes: integer("size_bytes").notNull().default(0),
    /** One of ARTIFACT_JOB_STATUSES — set only by create route + worker. */
    status: text("status").notNull().default("pending"),
    /** Neutral 1–2 sentence description of what was generated (worker output). */
    summary: text("summary"),
    /** Failure reason when status is "failed" — surfaced to the operator. */
    error: text("error"),
    startedAt: timestamp("started_at", { withTimezone: true }),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("engram_artifacts_engram_idx").on(t.engramId),
    index("engram_artifacts_status_idx").on(t.status),
    index("engram_artifacts_conversation_idx").on(t.conversationId),
  ],
);

/**
 * Raw bytes of a generated artifact, kept in a separate 1:1 table so the metadata
 * table can be listed/polled without ever loading file contents.
 */
export const engramArtifactBlobsTable = pgTable("engram_artifact_blobs", {
  artifactId: integer("artifact_id")
    .primaryKey()
    .references(() => engramArtifactsTable.id, { onDelete: "cascade" }),
  data: bytea("data").notNull(),
});

export const insertEngramArtifactSchema = createInsertSchema(
  engramArtifactsTable,
).omit({ id: true, createdAt: true, updatedAt: true });
export type InsertEngramArtifact = z.infer<typeof insertEngramArtifactSchema>;
export type EngramArtifact = typeof engramArtifactsTable.$inferSelect;
export type NewEngramArtifact = typeof engramArtifactsTable.$inferInsert;
